ActivityManager/urls.py
from django.conf.urls import url
from ActivityManager.views import TimetableView, create_session, unenroll, enroll, get_session_details, delete_session

app_name = "ActivityManager"

urlpatterns = [
    url(r'^$', TimetableView.as_view(), name="timetable_view"),
    url(r'^session/create/$', create_session, name="session_create"),
    url(r'^session/(?P<session_id>[0-9]*)/unenroll/$', unenroll, name="unenroll"),
    url(r'^session/(?P<session_id>[0-9]*)/enroll/$', enroll, name="enroll"),
    url(r'^session/(?P<session_id>[0-9]*)/delete/$', delete_session, name="session_delete"),
    url(r'^session/(?P<session_id>[0-9]*)/$', get_session_details, name="session_details"),
]

GymManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('activities/', include('ActivityManager.urls', 'activitymanager')),
    path('accounts/login/', auth_views.LoginView.as_view(), name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', RedirectView.as_view(url='/activities'))
]

ActivityManager/models.py
from django.contrib.auth.models import User
from django.db import models


class Activity(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    max_assistants = models.SmallIntegerField()

    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=50)
    max_assistants = models.SmallIntegerField()

    def __str__(self):
        return self.name


class Session(models.Model):
    activity = models.ForeignKey(Activity, null=False, blank=False, on_delete=models.PROTECT)
    room = models.ForeignKey(Room, null=False, blank=False, on_delete=models.PROTECT)
    timestamp = models.DateTimeField(null=False, blank=False)
    trainer = models.ForeignKey(User, null=False, blank=False, on_delete=models.SET("[deleted]"))

    def __str__(self):
        return self.activity.name + " in " + self.room.name + " at " + self.timestamp.isoformat()


class SessionUserControl(models.Model):
    session = models.ForeignKey(Session, null=False, blank=False, on_delete=models.PROTECT)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.id) + " - " + str(self.session) + " - " + self.user.username

ActivityManager/forms.py
from datetime import datetime, time

from django.forms import ModelForm, DateTimeField, forms

from ActivityManager.models import Session, SessionUserControl
from GymManager.settings import OPEN_HOURS


class SessionForm(ModelForm):
    timestamp = DateTimeField(disabled=True, initial=datetime.now())

    class Meta:
        model = Session
        exclude = ('trainer', 'timestamp')

    def is_valid(self):
        if not super().is_valid():
            return False

        timestamp = self.cleaned_data['timestamp']
        start_time, end_time = OPEN_HOURS

        if (
            timestamp.time().replace(hour=0) != time(0, 0, 0) or  # Check that time is a whole hour
            timestamp.weekday() > 4 or  # Check that day is workday
            timestamp.hour < start_time or timestamp.hour > end_time or  # Check that time is in the timetable
            timestamp < datetime.now()  # Check that time is after now
        ):
            return False

        same_time_sessions = Session.objects.filter(timestamp__exact=timestamp)
        if (
            len(same_time_sessions.filter(room__exact=self.cleaned_data['room']))  # No sessions in same room
        ):
            self.errors['room'] = ["Room is occupied at this time"]
            return False
        return True

    def clean(self):
        clean_data = super().clean()
        try:
            clean_datetime = datetime.strptime(self.data['timestamp'], '%d/%m/%y - %H:%M')
        except ValueError:
            raise forms.ValidationError("Wrong format for timestamp")
        clean_data['timestamp'] = clean_datetime
        return clean_data


class EnrolmentForm(ModelForm):
    class Meta:
        model = SessionUserControl
        exclude = ('user',)

ActivityManager/views.py
from datetime import *
from urllib.parse import parse_qs
import json

import django.http as http
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.template.defaulttags import register
from django.views.generic import ListView
from django.forms.models import model_to_dict

from ActivityManager.forms import SessionForm, EnrolmentForm
from ActivityManager.models import Session, SessionUserControl
from GymManager.settings import OPEN_HOURS


def format_hour(hour):
    return "%s:00" % str(hour).zfill(2)


def get_week_start(timestamp):
    timestamp = timestamp.date()
    return timestamp - timedelta(days=timestamp.weekday())


def assists_session(session, user):
    if not user.is_authenticated:
        return False
    return \
        len(SessionUserControl.objects.filter(session=session, user=user)) > 0 or \
        session.trainer == user


def filter_element(collection, element_id):
    candidates = collection.objects.filter(id=element_id)
    if not candidates.exists():
        return False, http.HttpResponseNotFound()

    candidates = candidates.filter(timestamp__gt=datetime.now())
    if not candidates.exists():
        return False, http.HttpResponseGone()
    return True, candidates.first()


def get_week(user, week_start):
    """
    Timetable object structure is:
    {
        <day (timestamp)>: {
            <time (string)>: [
                {
                    'session': <Session>,
                    'assisting': <boolean>
                }, ...
            ]
        }
    }
    """
    open_time, close_time = OPEN_HOURS
    week_end = week_start + timedelta(weeks=1)
    sessions = Session.objects.filter(timestamp__gte=week_start, timestamp__lt=week_end)
    timetable = {}

    for day in [week_start + timedelta(days=i) for i in range(5)]:
        for hour in range(open_time, close_time):
            timestamp = datetime.combine(day, time(hour=hour))
            timetable[timestamp] = list(map(
                lambda sess: {
                    'session': sess,
                    'assisting': assists_session(sess, user)
                },
                sessions.filter(timestamp__exact=timestamp)
            ))
    return timetable


@register.filter
def combine(d, t):
    return datetime.combine(d, t)


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@register.filter
def has_group(user, group_name):
    query = Group.objects.filter(name=group_name)
    if not query.exists():
        return False
    else:
        return query.first() in user.groups.all()


@register.filter
def disable_if_is_before(time1, time2):
    if time1 < time2:
        return "disabled"
    else:
        return ""


class TimetableView(ListView):
    model = Session
    template_name = 'ActivityManager/timetable.html'

    def get_context_data(self, **kwargs):
        current_week = get_week_start(datetime.now())
        selected_week = current_week
        open_time, close_time = OPEN_HOURS

        query_string = parse_qs(self.request.GET.urlencode())
        if 'week' in query_string and len(query_string['week']) == 1:
            try:
                timestamp = int(query_string['week'][0].strip('/'))
                selected_week = get_week_start(datetime.fromtimestamp(timestamp))
                if selected_week < current_week:
                    selected_week = current_week
            except ValueError:
                pass

        context = super().get_context_data(**kwargs)
        context['timetable'] = get_week(self.request.user, selected_week)
        context['days'] = list(map(lambda i: selected_week + timedelta(days=i), range(5)))
        context['times'] = [time(hour=hour) for hour in list(range(open_time, close_time))]

        context['form'] = SessionForm()

        context['week'] = {
            'now': int(datetime.timestamp(datetime.combine(current_week, time()))),
            'prev': int(datetime.timestamp(datetime.combine(selected_week - timedelta(days=7), time()))),
            'curr': int(datetime.timestamp(datetime.combine(selected_week, time()))),
            'next': int(datetime.timestamp(datetime.combine(selected_week + timedelta(days=7), time())))
        }
        context['now'] = datetime.now()
        return context


@login_required(redirect_field_name='/activities')
def create_session(request):
    if not has_group(request.user, 'trainer'):
        return http.HttpResponseForbidden()
    form = SessionForm(request.POST)
    if form.is_valid():
        form_data = form.cleaned_data
        if len(Session.objects.filter(trainer__exact=request.user, timestamp__exact=form_data['timestamp'])):
            return http.HttpResponseBadRequest("A session already exists for you at this time")
        Session(
            trainer=request.user,
            timestamp=form_data['timestamp'],
            room=form_data['room'],
            activity=form_data['activity']
        ).save()
        return http.HttpResponse()

    errors = []
    for error in form.errors.keys():
        for message in form.errors[error]:
            errors.append("%s: %s" % (error, message))
    return http.HttpResponseBadRequest(json.dumps(errors))


@login_required(redirect_field_name='/activities')
def delete_session(request, session_id):
    # We check here so that user does not get info about the error if they are not trainer
    if not has_group(request.user, 'trainer'):
        return http.HttpResponseForbidden()

    found, session = filter_element(Session, session_id)
    if not found:
        return session

    if session.trainer != request.user:
        return http.HttpResponseForbidden()
    session.delete()
    return http.HttpResponse()


@login_required(redirect_field_name='/activities')
def enroll(request, session_id):
    if not has_group(request.user, 'client'):
        return http.HttpResponseForbidden()

    found, session = filter_element(Session, session_id)
    if not found:
        return session

    # Check if user already has an activity at this time
    if len(SessionUserControl.objects.filter(user=request.user, session__timestamp__exact=session.timestamp)):
        return http.HttpResponseBadRequest("An enrolment at this time already exists")

    # Check if session is full
    num_assistants = len(SessionUserControl.objects.filter(session=session))
    max_assistants = min(session.room.max_assistants, session.activity.max_assistants)
    if num_assistants == max_assistants:
        return http.HttpResponseBadRequest("Session is full")

    SessionUserControl(
        user=request.user,
        session=session
    ).save()
    return http.HttpResponse()


@login_required(redirect_field_name='/activities')
def unenroll(request, session_id):
    # No user filtering needed because only clients can enroll anyway
    found, session = filter_element(Session, session_id)
    if not found:
        return session

    SessionUserControl.objects.filter(user=request.user, session=session).delete()
    return http.HttpResponse()


def get_session_details(request, session_id):
    sess_list = Session.objects.filter(id=session_id)
    if len(sess_list) == 0:
        return http.HttpResponseNotFound()

    sess = sess_list.first()
    return http.HttpResponse(json.dumps({
        'activity': sess.activity.name,
        'room': sess.room.name,
        'trainer': sess.trainer.username,
        'max_assistants': min(sess.activity.max_assistants, sess.room.max_assistants),
        'assistants': list(map(
            lambda enrolment: enrolment.user.username,
            SessionUserControl.objects.filter(session=sess)
        ))
    }))

templates/ActivityManager/timetable.html
{% extends "base.html" %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: rgba(0, 0, 255, 0.05);
        }

        .table-responsive {
            padding: 2%;
        }
    </style>

    <!-- Table legend and navigation buttons -->
    <div class="row justify-content-end row-button">
        <div class="col-4 legend">
            <p id="clock" class="legend-text">{{ now }}</p>
        </div>
        <div class="col-2 legend assisting">
            <p class="legend-text">Sessions in which you participate</p>
        </div>
        <div class="col-2 legend session">
            <p class="legend-text">Sessions in which you do not participate</p>
        </div>

        <div class="col-1">
            <form method="get" action={% url 'activitymanager:timetable_view' %}>
                <input type="hidden" name="week" value={{ week.prev }}/>
                <button {{ week.prev|disable_if_is_before:week.now }} class="btn btn-default">&laquo; Previous week
                </button>
            </form>
        </div>
        <div class="col-1">
            <form method="get" action={% url 'activitymanager:timetable_view' %}>
                <button type="submit" class="btn btn-default">Back to today</button>
            </form>
        </div>
        <div class="col-1">
            <form method="get" action={% url 'activitymanager:timetable_view' %}>
                <input type="hidden" name="week" value={{ week.next }}/>
                <button type="submit" class="btn btn-default">Next week &raquo;</button>
            </form>
        </div>
    </div>

    <!-- Data table -->
    <div class="table-responsive">
        <table class="table">
            <tr>
                <th> Hour / Day</th>
                {% for day in days %}
                    <th> {{ day|date:"D d/m" }}</th>
                {% endfor %}
            </tr>

            {% for time in times %}
                <tr>
                    <td>{{ time|time:"H:i" }}</td>
                    {% for day in days %}
                        {% with datetime=day|combine:time %}
                            <td>
                                {% for session in timetable|get_item:datetime %}
                                    {% if session.assisting %}
                                        <div class="assisting">
                                    {% elif session.trainer.username == request.user.username %}
                                        <div class="session-own">
                                    {% else %}
                                        <div class="session">
                                    {% endif %}
                                <button
                                        type="button" data-toggle="modal" id="{{ session.session.pk }}"
                                        data-target="#userModal" class="btn btn-link btn-sm btn-user"
                                        {{ datetime|disable_if_is_before:now }}>
                                    {{ session.session.activity.name }} - {{ session.session.room.name }}
                                </button>
                                </div>
                                {% empty %}

                                {% endfor %}
                                <div class=col-12 style="text-align: center;">
                                    {% if request.user|has_group:"trainer" %}
                                        {% if user.is_authenticated %}
                                            <button
                                                    type="button" data-toggle="modal"
                                                    data-target="#trainerModal"
                                                    class="btn btn-link btn-sm btn-trainer block"
                                                    {{ datetime|disable_if_is_before:now }}
                                                    title="{{ datetime|date:"d/m/y - H:i" }}"><span
                                                    class="glyphicon glyphicon-plus"></span>
                                            </button>
                                        {% else %}
                                            <a
                                                    type="button" href="{% url 'login' %}?next=/activities"
                                                    class="btn btn-link btn-sm block"> <span
                                                    class="glyphicon glyphicon-plus"></span>
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </td>
                        {% endwith %}
                    {% endfor %}
                </tr>
            {% endfor %}

        </table>
    </div>
    {% include 'ActivityManager/trainermodal.html' %}
    {% include 'ActivityManager/usermodal.html' %}
    <script>
        // Set time updater
        function updateTime() {
            const datetime = new Date();
            $("#clock").text(
                datetime.toUTCString().slice(0, -4)
            );
            setTimeout(updateTime, 1000);
        }

        updateTime();

        // Set behaviour on form submission
        $(".btn-submit").click(function(event) {
            event.preventDefault();

            // Prepare data object
            const formData = $(event.target.form).serializeArray();
            const data = {};
            for (let i = 0; i < formData.length; i++) {
                data[formData[i].name] = formData[i].value;
            }

            // Add timestamp if necessary
            const timestamp = $("#id_timestamp").val();
            if (timestamp) {
                data.timestamp = timestamp;
            }

            // Post and get result
            $.post(event.target.form.action, data)
            .done(function() {
                location.reload();
            })
            .fail(function(response) {
                response = $.parseJSON(response.responseText);
                const error_list = [];
                for (let i = 0; i < response.length; i++) {
                    error_list.push('<li class="error-text">' + response[i] + '</li>')
                }
                $(".error-field").html(error_list.join(''));
                setTimeout(function() {
                    $(".error-field").html("&nbsp;");
                }, 2000);
            });
        });

        // Populate session modal when opened
        $(".btn-trainer").click(function (event) {
            const content = event.target.title || event.target.parentElement.title;
            $("#trainerModal .modal-title").text(content);
            $("#id_timestamp").val(content);
        });

        // Populate user modal when opened
        $(".btn-user").click(function (event) {
            $.getJSON('session/' + event.target.id, function (data) {
                // Set descriptive items
                $("#userModal .modal-title").text(data.activity);
                $("#userModal #trainer").text('Trainer: ' + data.trainer);
                $("#userModal #room").text(data.room);
                $("#userModal #assistants").text('Assistants (' + data.assistants.length + '/' + data.max_assistants + '):');

                let assistantList = [];
                $.each(data.assistants, function (id, assistant) {
                    assistantList.push('<li>' + assistant + '</li>')
                });
                $("#userModal #assistantList").html(assistantList.join(''));

                // Set enrolment (if user) or delete (if trainer) button
                {% if request.user|has_group:"client" %}
                    const enrolment_string = data.assistants.includes("{{ request.user.username }}") ? 'Unenroll' : 'Enroll';
                    $("#userModal #enrolment").attr('action', 'session/' + event.target.id + '/' + enrolment_string.toLowerCase() + '/');
                    $("#userModal #enrolment button").text(enrolment_string);
                    if (data.assistants.length < data.max_assistants) $("#userModal #enrolment button").attr('disabled', false);

                {% elif request.user|has_group:"trainer" %}
                    $("#userModal #enrolment").attr('action', 'session/' + event.target.id + '/delete/');
                    $("#userModal #enrolment button").text("Delete");
                    if (
                        data.trainer === "{{ user.username }}" &&
                        data.assistants.length === 0
                    ) $("#userModal #enrolment button").attr('disabled', false);
                {% endif %}
            })
        });
    </script>
{% endblock %}

templates/ActivityManager/trainermodal.html
<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="trainerModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <form id="session_form" method="post" action={% url 'activitymanager:session_create' %}>
                    {% csrf_token %}
                    <div class="modal-header">
                        <h4 class="modal-title" id="modal-title">Modal Header</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <table>
                            {{ form.as_table }}
                        </table>
                        <ul class="error-field">&nbsp;</ul>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default btn-submit">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

templates/ActivityManager/usermodal.html
<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="userModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Modal Header</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p id="trainer">Trainer: ?</p>
                    <p id="room"></p>
                    <p id="assistants">Assistants:</p>
                    <ol id="assistantList"></ol>
                    <p class="error-field">&nbsp;</p>
                </div>
                <div class="modal-footer">
                    <form id="enrolment" method="post" action="#">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-submit" disabled>Action</button>
                    </form>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
</div>